### ISSUE TITLE
To test the algorithms extensions

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#11]
Description:
The FML extension analyzes text complexity. At the moment, there are 2 algorithms that determine the complexity of the text. 1 - 1000 English words used, 2 - according to a special formula (the length of sentences, the number of syllables in a word). 

link to the description of the second algorithm https://ru.wikipedia.org/wiki/Индекс_удобочитаемости

Task: find out which algorithm determines the complexity of the text more correctly. To do this, you need to find texts with a given level of complexity (language level-A1, A2.....C2). You need to check the texts using 2 algorithms.

release 2 files to install the local extension. In the file name, specify the difference between extensions (by what principle @Sabbaken determines the level of complexity)
@MikeRogovskiy test the extension with different algorithms on special texts

**Comment by sabbaken** [comment]
[find_my_level_new_algorithm.zip](https://github.com/easably/FindMyLevel/files/5831185/find_my_level_new_algorithm.zip)

[find_my_level_old_algorithm.zip](https://github.com/easably/FindMyLevel/files/5831188/find_my_level_old_algorithm.zip)
