### ISSUE TITLE
[3per day] Build a database of eLang-TV videos using the FML 2.0 extension

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#13]
Description:
Use the FL extension of 2.0 to assemble the base of videos for elangtv

**Comment by alexnpol** [comment]
данные для входа

{
"key": "GCX4yd",
"name": "artyom_sivko"
}

**Comment by I-am-Artyom** [comment]
Due to the improper work of FML, it's difficult to collect the majority of YT videos

**Comment by I-am-Artyom** [comment]
The extension is currently broken

**Comment by MikeRogovskiy** [comment]
@I-am-Artyom  
Pavel repaired this build
