### ISSUE TITLE
Create a base token for authorization in the extension

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#18]
Description:
FML extension to collect videos in the elangTV database. This will happen under the control of the editor. In order for the editor to use the extension, he must log in to it. To do this, it must have a token (authorization occurs with a token).

Create a base token that can be changed for each editor. It is desirable that the token contains the first or last name of the editor.

**Comment by ZhuchkouAA** [comment]
![Screenshot 2021-02-22 at 13 53 47](https://user-images.githubusercontent.com/56683813/108698692-773a3b00-7515-11eb-977d-f79c6f8dbea8.png)
