### ISSUE TITLE
[4h]Create a flow for the situation when the editor adds a video to elangTV 

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#21]
Description:
We have the UML 2.0 extension. The editor uses the extension to add videos from YouTube to the elangTV video database. The editor can assign a Category for the video in the extension itself and this video will appear in the same Category in elangTV.

Task: Create a workflow from the moment you open the extension on YouTube and the video appears in the elangTV database.

![image](https://user-images.githubusercontent.com/70699061/111600528-8f366f00-87e2-11eb-9395-173363eab113.png)

**Comment by NikaPipchenko** [comment]
@alexnpol 
We haven't API key. It's block our work.

When we gets it, we continue our work.

**Comment by NikaPipchenko** [comment]
https://www.figma.com/file/iWxiePHzNfCFrLCduxN0Uo/Artifacts?node-id=1138%3A194&viewport=593%2C417%2C0.3116642236709595
