### ISSUE TITLE
[4h] Create a wireframe tab to add a video segment to elangTV

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#22]
Description:
At the moment, the tab should only contain a list of words that were marked with the video and a button that will allow you to send these words to the database If you have suggestions for what else to show in this window, you can draw on the wireframe but do not reload the window - only the words are important.

![image](https://user-images.githubusercontent.com/70699061/111599480-5fd33280-87e1-11eb-822c-440c91e5131c.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/iWxiePHzNfCFrLCduxN0Uo/Artifacts?node-id=1144%3A693

![image](https://user-images.githubusercontent.com/58423687/111634390-8310d880-8807-11eb-914e-c8fe9faac9f5.png)
