### ISSUE TITLE
Create a flow for the situation when the editor adds a video to Fillwords2

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#23]
Description:
At the moment, the tab should only contain a list of words that were marked with the video and a button that will allow you to send these words to the database If you have suggestions for what else to show in this window, you can draw on the wireframe but do not reload the window - only the words are important.

![image](https://user-images.githubusercontent.com/70699061/111600842-d6246480-87e2-11eb-801a-7e36d763968a.png)

**Comment by annamaksimik** [comment]
https://www.figma.com/file/iWxiePHzNfCFrLCduxN0Uo/Artifacts?node-id=1144%3A693

![image](https://user-images.githubusercontent.com/58423687/111634390-8310d880-8807-11eb-914e-c8fe9faac9f5.png)
