### ISSUE TITLE
[3h]Расширение eLang tool не работает с видео, у которых английские субтитры имеют название отличное от English

### ISSUE THREAD

**Issue by alexkovaluoff** [easably/FindMyLevel#26]
Например:
eLang tool не работает для [видео](https://www.youtube.com/watch?v=TEFqEr7HGX4&ab_channel=WIRED), у которого название субтитров помимо English имеет другие слова
![image](https://user-images.githubusercontent.com/83351704/129029949-3273bfb9-71da-4197-8af5-71e2694f3915.png)
![image](https://user-images.githubusercontent.com/83351704/129030225-a65f5f63-043b-49cd-b5f9-a3331ca2d055.png)

**Comment by pavel232** [comment]
https://github.com/easably/elang-tool/releases/tag/0.0.4
