### ISSUE TITLE
Create an icon (logo) for the Find My Level extension

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#4]
Description:
Create a logo icon for the extension Find My Level

**Comment by annamaksimik** [comment]
![image](https://user-images.githubusercontent.com/58423687/103280492-9c14a500-49e1-11eb-83b5-d747b0c34120.png)

**Comment by annamaksimik** [comment]
[Logo.zip](https://github.com/easably/FindMyLevel/files/5750778/Logo.zip)
