### ISSUE TITLE
Write text for pop-up windows

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#5]
Description:
You need to explain to the user what thousand words we are talking about

![image](https://user-images.githubusercontent.com/70699061/103280013-586d6b80-49e0-11eb-96dd-78836bcecba4.png)

**Comment by I-am-Artyom** [comment]
EN
Common thousand - 1000 most popular words, used in everyday English. 
Second thousand of English words most frequently spoken. 

RU
Тысяча часто употребляемых слов в английском языке.
Вторая тысяча самых популярных английских слов.
