### ISSUE TITLE
Make Russian and English versions of the text in the extension

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#6]
Description:
Write text for English and Russian extensions
![image](https://user-images.githubusercontent.com/70699061/103280542-b8184680-49e1-11eb-8852-af7f1c813ab5.png)

![image](https://user-images.githubusercontent.com/70699061/103280683-0cbbc180-49e2-11eb-90c8-9e2578530864.png)

**Comment by I-am-Artyom** [comment]
RU-EN (only lower ad)
Films and series in English with dual subtitles
Learn about it!

EN-RU
Сложность текста: Простой / Средний / Тяжёлый
Всего слов
Слов из первой тысячи
Слов из второй тысячи
