### ISSUE TITLE
Write a text description for the FML extension

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#7]
Description:
Write the text to describe the extension in google chrome. Write the text in Russian and reset it to make edits

**Comment by I-am-Artyom** [comment]
The file is here https://docs.google.com/document/d/1jWIKXp4jx-eLlrErZkteGFN_BQm_4BFAi6RU6ERNp7E/edit

Dunno if people are going to approve it, so I am ready to change it later.
