### ISSUE TITLE
Determine the final name for the extension

### ISSUE THREAD

**Issue by alexnpol** [easably/FindMyLevel#9]
Description:
while writing the description of the extension, there were suggestions for changing the name. It is necessary to offer several variants of the name and choose the final one.

**Comment by I-am-Artyom** [comment]
### Feasible alternatives proposed by Sergey, (Svet)Lana, and me

- FindTextLevel
- TextLevel
- CanIReadIt
- LevelYoText
- LevelMyText

My suggestion: _**LevelMyText**_
